name = "shy-recipe-5fb1"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "EventBingoProgress"
bucket_name = "eventbingo-progress"
preview_bucket_name = "eventbingo-progress-preview"
