name = "shy-recipe-5fb1"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV for event metadata and photo URL references
[[kv_namespaces]]
binding = "EventBingoProgress"
id = "082374632841442ca7f22633a707b372"
preview_id = "082374632841442ca7f22633a707b372"

# R2 for actual photo file storage
[[r2_buckets]]
binding = "EventBingoPhotos"
bucket_name = "eventbingophotos"
preview_bucket_name = "eventbingophotos-preview"
